version: '3.8'

services:
  web:
    build: .
    container_name: fullstack_academy_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./Hitler/Backend/db.sqlite3:/app/Backend/db.sqlite3
