# Generated by Django 6.0.3 on 2026-08-15 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_default_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('isPopular', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('badgeColor', models.CharField(blank=True, max_length=100)),
                ('mentorName', models.CharField(blank=True, max_length=100)),
                ('mentorRole', models.CharField(blank=True, max_length=100)),
                ('mentorExp', models.CharField(blank=True, max_length=100)),
                ('mentorGrad', models.CharField(blank=True, max_length=200)),
                ('mentorInitials', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('grad', models.CharField(blank=True, max_length=200)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.course')),
            ],
        ),
    ]
